groups:
  - id: span.gen_ai.invoke_workflow.client
    type: span
    stability: development
    span_kind: client
    brief: >
      Describes GenAI workflow invocation.
    note: |
      The `gen_ai.operation.name` SHOULD be `invoke_workflow`.

      **Span name** SHOULD be `invoke_workflow {gen_ai.workflow.name}` if `gen_ai.workflow.name` is readily available.
      When `gen_ai.workflow.name` is not available, it SHOULD be `invoke_workflow`.

      **Span kind** SHOULD be `CLIENT` and MAY be set to `INTERNAL` on spans representing
      invocation of workflows running in the same process.
    extends: attributes.gen_ai.common.client
    attributes:
      - ref: gen_ai.provider.name
        requirement_level: required
        sampling_relevant: true
      - ref: gen_ai.operation.name
        sampling_relevant: true
      - ref: gen_ai.workflow.name
        requirement_level: required
        sampling_relevant: true
      - ref: gen_ai.input.messages
        requirement_level: opt_in
      - ref: gen_ai.output.messages
        requirement_level: opt_in
      - ref: error.type
        requirement_level:
          conditionally_required: "if the operation ended in an error"

  - id: metric.gen_ai.workflow.duration
    type: metric
    metric_name: gen_ai.workflow.duration
    annotations:
      code_generation:
        metric_value_type: double
    brief: 'GenAI workflow invocation duration.'
    instrument: histogram
    unit: "ms"
    stability: development
    extends: metric_attributes.gen_ai
    attributes:
      - ref: gen_ai.workflow.name
        requirement_level: required
      - ref: error.type
        requirement_level:
          conditionally_required: "if the operation ended in an error"
